Update trinkets.py
NerdEgghead/WotLK_cat_sim pull request #12
Opened 2023-02-18 23:15 UTC by Timothy-Page

Updated for the new values of the trinkets to match the latest patch

2023-02-19 01:19 UTC, Timothy-Page commented
I have added the t9 set bonus into the sim

2023-02-19 02:21 UTC, Timothy-Page commented
added the new feral idol

2023-02-21 21:16 UTC, NerdEgghead requested changes
Thanks a lot! Made some comments, mostly minor stylistic stuff but some errors as well.

2023-02-21 21:16 UTC, NerdEgghead commented on main.py
> +            {'label': 'Idol of Mutilation', 'value': 'idol_of_Mutilation'},
would keep lowercase here on "mutilation" for consistency

2023-02-21 21:16 UTC, NerdEgghead commented on main.py
> +            proc_duration=16, cooldown=0, proc_name='Mutilation',
Idol of Mutilation has an ICD of 8 seconds, so cooldown here should be 8

2023-02-21 21:16 UTC, NerdEgghead commented on main.py
> +                    'value': 'Deaths Verdict heroic',
Would keep the same style convention here for the value field as for the other trinkets just for consistency (no caps, underscore instead of spaces)

2023-02-21 21:16 UTC, NerdEgghead commented on trinkets.py
> +            'proc_name': 'Darkmoon Card: Greatness',
would make the proc_name field here either "Death's Verdict" or whatever the actual name of the proc buff is, helps with making the sim logs clearer

2023-02-21 21:16 UTC, NerdEgghead commented on player.py
> +        self.lacerate_dot_multi = 0.05 * t9_2p
should be 1 plus this for the math to work out properly

2023-02-21 21:16 UTC, NerdEgghead commented on player.py
> +        self.rip_crit = 0.05 * t9_4p
Would rename these to "bite_crit_bonus" and "rip_crit_bonus" for clarity

2023-02-22 00:11 UTC, merged